### PR TITLE
Add documentation workflow and contributing

### LINKED ISSUE #34: Missing contributing documentation
Hi,

I've been trying to add a "Note" question type to print question section headers or something like that, but I'm having fundamental questions getting the tests running. Can you provide a couple of lines in a readme for how you set up your python environment for test cases?

This is what I'm getting at the moment with no changes to the master branch. Is this expected?

https://gist.github.com/drewsonne/2d3083310e82f7b4302149fb353bfff3

### LINKED ISSUE #51: Update ReadTheDocs
ReadTheDocs were not updated at least since you have released my Path question contribution, because there is no information about this question, but I have added documentation for it...

### PR DESCRIPTION
**Pull request by staticdev**
Closes #34 
Closes #51

### CODE REVIEW

**Comment by staticdev** [comment]
@magmax could you please add me also as maintainer to this project in ReadTheDocs.org? I think some settings to this project may be wrong since my pipeline is not updating it properly.

**Comment by magmax** [comment]
> @magmax could you please add me also as maintainer to this project in ReadTheDocs.org? I think some settings to this project may be wrong since my pipeline is not updating it properly.

I assumed your user in readthedocs.org is `staticdev` as well... added.

**Comment by staticdev** [comment]
@magmax that is right! I will try to troubleshoot..

**Comment by staticdev** [comment]
@magmax I was able to create a new version of the docs on https://python-inquirer.readthedocs.io/en/latest/
Not really sure how you setup the redirect to https://magmax.org/python-inquirer/ (but it was not updated).

**Pull request merged**
