### PR TITLE
Add import path shortcut to __init__,py

### PR DESCRIPTION
**Pull request by balac-ode**
Add import path shortcut to `__init__,py`

### CODE REVIEW

**Review by staticdev — CHANGES_REQUESTED** [review]
Please keep the alphabetical order on imports.

**Comment by Cube707** [comment]
@balac-ode It would be great if you rebased onto master and ran `pre-commit`. This now includes `isort` and will sort the imports for you.

Once that is done we can merge this 👍🏼

**Comment by staticdev** [comment]
@Cube707 looks like this user abandoned github after this PR...

**Comment by Cube707** [comment]
You're probably right, he doesn't seem to be active. Lets give him a couple more day and that we can close this.

**Comment by Cube707** [comment]
Suggested edit:
```diff
diff --git a/src/inquirer/__init__.py b/src/inquirer/__init__.py
index 206d337..16deadf 100644
--- a/src/inquirer/__init__.py
+++ b/src/inquirer/__init__.py
@@ -14,8 +14,8 @@ from inquirer.shortcuts import confirm
 from inquirer.shortcuts import editor
 from inquirer.shortcuts import list_input
 from inquirer.shortcuts import password
-from inquirer.shortcuts import text
 from inquirer.shortcuts import path
+from inquirer.shortcuts import text
 
 
 __all__ = [
@@ -35,5 +35,6 @@ __all__ = [
     "password",
     "confirm",
     "list_input",
+    "path",
     "checkbox",
 ]

```

**Comment by Cube707** [comment]
I just experimented with the VS code integration of GitHub PRs and how one can suggest and/or push chnages....

**Comment by Cube707** [comment]
closed due to inactivity

**Pull request closed without merging**
