### PR TITLE
Fix issue #14

### PR DESCRIPTION
**Pull request by lelit**

### CODE REVIEW

**Comment by lelit** [comment]
@magmax, the failure is not related to my changes, is this acceptable or should I take care of those too?

**Comment by magmax** [comment]
Lovely new flakes...

It should be fixed at master. Could you kindly rebase origin/master?

**Comment by lelit** [comment]
Ok, done! I think that the coverage decrease is not my fault... ;-)

**Comment by magmax** [comment]
The coverage decrease *is* your fault, due to the refactor on `password.py`: less code tested against non-tested (because it is being reused).

Anyway, codecoverage should be taken in mind carefully and -0.2 is noting :)

**Comment by lelit** [comment]
Thank you Miguel.
WRT to the coverage: I'm afraid fail to understand the coverage report then: it shows that the _password.py is 100% covered, so how can that _decrease_ the overall status?

**Pull request merged**
