### PR TITLE
Introduction of Path question

### PR DESCRIPTION
**Pull request by AuHau**
Adding new question for Paths and its verifications.
Its main features:
 * Expand home (eq. '~/some/path' to '/home/some_user/some/path) correctly according to OS
 * Enables to enforce existence and non-existence of the path
 * Enables verification of the path type (file vs. directory)
 * Does proper path validation across supported OSs

Please let me know if you want to merge this to your repo, if so I will polish it more (eq. tests coverage, docs etc.)

### CODE REVIEW

**Comment by AuHau** [comment]
Hmm I just noticed that there is some similar work in #41 
Since there was not an update since March, I could integrate it in my PR, with @djf604 permissions...

**Comment by magmax** [comment]
I love this feature. Please, do it and fix the travis problems; it is easy, just a couple of flakes ;)

**Comment by djf604** [comment]
Hi! So I wrote some similar Path features a couple months back, but it failed some tests and I never really looked much into why or did anything after that (which was pure apathy and totally my bad). I think I add a couple more features than just the path stuff, but I'd have to go back and take a look at my commit messages to remember what all I implemented.

That being said I'm perfectly happy merging our work! Odds are there is some overlap but we can hopefully work that out.

**Comment by AuHau** [comment]
So from my side, this should be all :-) Let me know if you have some feedback about the code or anything else.

Regarding the @djf604 PR, I am really open on how to approach this. I would maybe suggest merging this PR as it should be pretty ready and then if @djf604 has time now, he can rebase and add his Path completion feature or if not, I could do it.

I took a quite similar approach when implementing the Path question, but I mostly focused on the validation part of the question, while @djf604 on the renderer...

**Comment by djf604** [comment]
Sure, give me a couple days to take a look at it and re-familiarize myself. I'll figure this out by the end of the weekend, sound good?

**Comment by AuHau** [comment]
@magmax any update on this? :-)

**Comment by magmax** [comment]
sorry for the delay. I missed those messages.

Thank you for your work and poking me :)

**Comment by AuHau** [comment]
Awesome, thanks! :-)

**Pull request merged**
