### PR TITLE
Add autocompletion for text prompts

### PR DESCRIPTION
**Pull request by WilliamVenner**
(Branches off of #256)

This adds the ability to add an autocompletion function to `Text` prompts. The autocompletion function has similar semantics as `readline.set_completer`. Pressing TAB will call the autocompletion function and set the current text to whatever it returns.

### CODE REVIEW

**Comment by Cube707** [comment]
@WilliamVenner please remove the merge. Instead, rebase your feature branch onto the current master and force push it  (after reafirming it still works)

**Comment by WilliamVenner** [comment]
Hey, do you need me to fix that code coverage thing? It seems a bit overzealous

**Comment by staticdev** [comment]
@WilliamVenner first of, autocompletion is a great feature and thanks for that.

I understand that is seems a overkill to have all this coverage, but also we are trying to maintain a well tested software so it is good for everyone. If you could add some unit tests for it would be great. If not, we see how we can deal with it and not loose also your effort.

**Comment by WilliamVenner** [comment]
Hmmm I'm having trouble of thinking how to come up with a test for this code, which I think is the culprit of the code coverage check fail. https://github.com/magmax/python-inquirer/blob/c4bbef7bfb99a03ca51834993ad63493eab7a712/src/inquirer/render/console/_text.py#L26-L39

I would be inclined to say that the test added by this PR and the already present tests should cover this code, but that's understandably not being picked up by the code coverage tool - any thoughts?

**Comment by staticdev** [comment]
@WilliamVenner  we have tests to render text here: https://github.com/magmax/python-inquirer/blob/main/tests/integration/console_render/test_text.py

I can add a case for autocomplete when you have tab key pressed.

**Comment by WilliamVenner** [comment]
Thanks for your help @staticdev :)

**Review by staticdev — APPROVED** [review]
Lgtm.

**Review by Cube707 — CHANGES_REQUESTED** [review]
I am missing some documentation. Code looks fine as is, but I tried fiddeling arround in the example and couldn't easiely get some basict to work:

- What is expected to be passed to `autocomplete`? 
- what do functons need to return when passed to autocomplete?

I tried the obvios thing and passed a list of strings, which just failed silently..

- an exapmle of using multiple suggestions would be helpful. Something similar to this:

```python
from itertools import cycle

global suggestions
suggestions = cycle(["inquirer", "hello"])
def autocomplete_fn(_text, _state):
    return next(suggestions)
```

**Comment by staticdev** [comment]
Thanks a lot @WilliamVenner !

**Comment by WilliamVenner** [comment]
hey guys, when do you plan on releasing this one? :p

**Pull request merged**
