### PR TITLE
Use readchar 0.0.9 for Python 3.6 support

### PR DESCRIPTION
**Pull request by danmichaelo**
See #36

### CODE REVIEW

**Comment by danmichaelo** [comment]
Ouch, seems like 0.1.0 fails on Python 2.7 (https://travis-ci.org/magmax/python-inquirer/jobs/340521473)

**Comment by danmichaelo** [comment]
reachar 0.0.8 and 0.0.9 seems to work with both Python 2.7 and Python 3.4+, I've modified my PR to use that version.

**Comment by magmax** [comment]
Version 0.0.9 is quite old.

Let's wait until it is fixed in readchar in order to upgrade it.

**Comment by danmichaelo** [comment]
Agree, now it seems like there is a chance for a new release

**Comment by AuHau** [comment]
The current version of readchar used is 2.0.1, so there is no need for this PR anymore, hence I am closing it. Feel free to object if you think it is still needed.

**Pull request closed without merging**
