### PR TITLE
text: implement DELETE

### PR DESCRIPTION
**Pull request by Cube707**
DELETE removes the letter in front of the coursor

### CODE REVIEW

**Review by staticdev — CHANGES_REQUESTED** [review]
Needs a test to pass the pipeline =p

**Comment by Cube707** [comment]
I completely forgot tests, lol

**Comment by Cube707** [comment]
I am still getting only 94% even with all my new codebranches coverd 🤷🏼‍♂️ 

image


I would say it's ready to merge.

**Review by staticdev — APPROVED** [review]

**Comment by staticdev** [comment]
This is ok, we don't have to be super strict. 94% is good anyways ;)

**Pull request merged**
